export type ICD10Entry = { code: string; description: string };

// WHO ICD-10 classification — Romanian translation (as per mediately.co/ro/icd)
export const ICD10_RO: ICD10Entry[] = [
  // ─── A00–B99  Boli infectioase si parazitare ──────────────────────────────
  { code: "A00.0", description: "Holera cu vibrio cholerae 01, biovar cholerae" },
  { code: "A00.1", description: "Holera cu vibrio cholerae 01, biovar eltor" },
  { code: "A00.9", description: "Holera, nespecificata" },
  { code: "A01.0", description: "Febra tifoida" },
  { code: "A01.1", description: "Paratifosul A" },
  { code: "A01.2", description: "Paratifosul B" },
  { code: "A01.3", description: "Paratifosul C" },
  { code: "A01.4", description: "Paratifos, nespecificat" },
  { code: "A02.0", description: "Enterita cu salmonella" },
  { code: "A02.1", description: "Sepsis cu salmonella" },
  { code: "A02.9", description: "Salmonelloza, nespecificata" },
  { code: "A04.5", description: "Enterita prin campylobacter" },
  { code: "A04.7", description: "Enterocolita prin clostridium difficile" },
  { code: "A04.9", description: "Infectia intestinala bacteriana, nespecificata" },
  { code: "A05.0", description: "Intoxicatia alimentara prin stafilococi" },
  { code: "A05.1", description: "Botulismul" },
  { code: "A05.9", description: "Intoxicatia alimentara de origine bacteriana, nespecificata" },
  { code: "A06.0", description: "Dizenteria amibiana acuta" },
  { code: "A06.9", description: "Amibiaza, nespecificata" },
  { code: "A07.1", description: "Giardiaza [lambliaza]" },
  { code: "A08.0", description: "Enterita prin rotavirus" },
  { code: "A09",   description: "Diareea si gastroenterita probabil infectioase" },
  { code: "A15.0", description: "Tuberculoza pulmonara, confirmata prin examen microscopic" },
  { code: "A15.3", description: "Tuberculoza pulmonara, confirmata prin metode nespecificate" },
  { code: "A15.9", description: "Tuberculoza cailor respiratorii, fara precizare" },
  { code: "A16.2", description: "Tuberculoza pulmonara, fara mentiunea confirmarii" },
  { code: "A16.9", description: "Tuberculoza cailor respiratorii, nespecificata" },
  { code: "A17.0", description: "Meningita tuberculoasa" },
  { code: "A18.0", description: "Tuberculoza oaselor si articulatiilor" },
  { code: "A18.1", description: "Tuberculoza aparatului genito-urinar" },
  { code: "A19.9", description: "Tuberculoza miliara, nespecificata" },
  { code: "A22.9", description: "Antrax, nespecificat" },
  { code: "A23.9", description: "Brucelloza, nespecificata" },
  { code: "A27.9", description: "Leptospiroza, nespecificata" },
  { code: "A33",   description: "Tetanosul nou-nascutului" },
  { code: "A35",   description: "Alte forme de tetanos" },
  { code: "A36.0", description: "Difteria faringiana" },
  { code: "A37.0", description: "Tusea convulsiva cu bordetella pertussis" },
  { code: "A38",   description: "Scarlatina" },
  { code: "A39.0", description: "Meningita meningococica" },
  { code: "A40.0", description: "Sepsis datorat streptococului, grupa A" },
  { code: "A40.3", description: "Sepsis datorat streptococcus pneumoniae" },
  { code: "A40.9", description: "Sepsis streptococic, nespecificat" },
  { code: "A41.0", description: "Sepsis datorat stafilococului auriu" },
  { code: "A41.9", description: "Sepsis, nespecificat" },
  { code: "A46",   description: "Erizipelul" },
  { code: "A48.0", description: "Gangrena gazoasa" },
  { code: "A48.3", description: "Sindromul de soc toxic" },
  { code: "A49.0", description: "Infectia stafilococica, nespecificata" },
  { code: "A49.9", description: "Infectia bacteriana, nespecificata" },
  { code: "A51.0", description: "Sifilis genital primar" },
  { code: "A54.9", description: "Infectia gonococica, nespecificata" },
  { code: "A59.0", description: "Trichomoniaza urogenitala" },
  { code: "A60.0", description: "Infectiile organelor genitale prin virusul herpetic" },
  { code: "A63.0", description: "Veruce ano-genitale (veneriene)" },
  { code: "A69.2", description: "Boala Lyme" },
  { code: "A78",   description: "Febra Q" },
  { code: "A80.9", description: "Poliomielita acuta, nespecificata" },
  { code: "A81.0", description: "Boala Creutzfeldt-Jakob" },
  { code: "A82.9", description: "Rabia, nespecificata" },
  { code: "A86",   description: "Encefalita virala, nespecificata" },
  { code: "A87.9", description: "Meningita virala, nespecificata" },
  { code: "A90",   description: "Denga (denga clasica)" },
  { code: "B00.1", description: "Dermita veziculara datorita virusului herpetic" },
  { code: "B00.9", description: "Infectia prin virusul herpetic, nespecificata" },
  { code: "B01.9", description: "Varicela fara complicatii" },
  { code: "B02.9", description: "Zona zoster, fara complicatii" },
  { code: "B05.9", description: "Rujeola, fara complicatii" },
  { code: "B06.9", description: "Rubeola, fara complicatii" },
  { code: "B07",   description: "Veruca de origine virala" },
  { code: "B08.1", description: "Molluscum contagiosum" },
  { code: "B15.9", description: "Hepatita A fara coma hepatica" },
  { code: "B16.9", description: "Hepatita acuta B, fara agent delta si fara coma hepatica" },
  { code: "B17.1", description: "Hepatita acuta C" },
  { code: "B18.1", description: "Hepatita virala cronica B, fara agent delta" },
  { code: "B18.2", description: "Hepatita virala cronica C" },
  { code: "B18.9", description: "Hepatita virala cronica, nespecificata" },
  { code: "B19.9", description: "Hepatita virala nespecificata, fara coma hepatica" },
  { code: "B24",   description: "Bolile prin virusul imunodeficientei umane nespecificate" },
  { code: "B26.9", description: "Oreionul fara complicatii" },
  { code: "B27.9", description: "Mononucleoza infectioasa, nespecificata" },
  { code: "B34.9", description: "Infectia virala, nespecificata" },
  { code: "B35.3", description: "Tinea piciorului" },
  { code: "B35.4", description: "Tinea corpului" },
  { code: "B36.0", description: "Pitiriazisul versicolor" },
  { code: "B37.0", description: "Stomatita candidozica" },
  { code: "B37.9", description: "Candidoza, nespecificata" },
  { code: "B49",   description: "Micoza, nespecificata" },
  { code: "B50.9", description: "Malaria cu plasmodium falciparum, nespecificata" },
  { code: "B54",   description: "Malaria, nespecificata" },
  { code: "B99",   description: "Alte boli infectioase si boli infectioase nespecificate" },

  // ─── C00–D48  Tumori ─────────────────────────────────────────────────────
  { code: "C00.9", description: "Tumora maligna a buzei, nespecificata" },
  { code: "C01",   description: "Tumora maligna a bazei limbii" },
  { code: "C10.9", description: "Tumora maligna a orofaringelui, nespecificata" },
  { code: "C11.9", description: "Tumora maligna a rinofaringelui, nespecificata" },
  { code: "C15.9", description: "Tumora maligna a esofagului, nespecificata" },
  { code: "C16.9", description: "Tumora maligna a stomacului, nespecificata" },
  { code: "C18.9", description: "Tumora maligna a colonului, nespecificata" },
  { code: "C19",   description: "Tumora maligna a jonctiiunii rectosigmoidiene" },
  { code: "C20",   description: "Tumora maligna a rectului" },
  { code: "C22.0", description: "Carcinomul hepatocelular" },
  { code: "C22.9", description: "Tumora maligna a ficatului, nespecificata" },
  { code: "C25.9", description: "Tumora maligna a pancreasului, nespecificata" },
  { code: "C34.1", description: "Tumora maligna a lobului superior, bronhie sau plaman" },
  { code: "C34.9", description: "Tumora maligna a bronhiei sau plamanului, nespecificata" },
  { code: "C43.9", description: "Melanomul malign al pielii, nespecificat" },
  { code: "C44.9", description: "Tumora maligna a pielii, nespecificata" },
  { code: "C50.9", description: "Tumora maligna a sanului, nespecificata" },
  { code: "C53.9", description: "Tumora maligna a colului uterin, nespecificata" },
  { code: "C54.1", description: "Tumora maligna a endometrului" },
  { code: "C56",   description: "Tumora maligna a ovarului" },
  { code: "C61",   description: "Tumora maligna a prostatei" },
  { code: "C62.9", description: "Tumora maligna a testiculului, nespecificata" },
  { code: "C64",   description: "Tumora maligna a rinichiului, cu exceptia pelvisului renal" },
  { code: "C67.9", description: "Tumora maligna a vezicii urinare, nespecificata" },
  { code: "C71.9", description: "Tumora maligna a creierului, nespecificata" },
  { code: "C73",   description: "Tumora maligna a glandei tiroide" },
  { code: "C80.9", description: "Tumora maligna, nespecificata" },
  { code: "C81.9", description: "Boala Hodgkin, nespecificata" },
  { code: "C82.9", description: "Limfomul folicular, nespecificat" },
  { code: "C83.9", description: "Limfomul non-folicular, nespecificat" },
  { code: "C85.9", description: "Limfomul non-Hodgkin, nespecificat" },
  { code: "C90.0", description: "Mielomul multiplu" },
  { code: "C91.0", description: "Leucemia limfoblastica acuta" },
  { code: "C91.1", description: "Leucemia limfocitara cronica" },
  { code: "C92.0", description: "Leucemia mieloblastica acuta" },
  { code: "C92.1", description: "Leucemia mieloida cronica" },
  { code: "D05.9", description: "Carcinomul in situ al sanului, nespecificat" },
  { code: "D10.0", description: "Tumora benigna a buzei" },
  { code: "D12.6", description: "Polipul colonului, nespecificat" },
  { code: "D21.9", description: "Tumora benigna a tesutului conjunctiv si al altor tesuturi moi" },
  { code: "D25.9", description: "Leiomiomul uterului, nespecificat" },
  { code: "D27",   description: "Tumora benigna a ovarului" },
  { code: "D35.2", description: "Tumora benigna a hipofizei" },
  { code: "D48.9", description: "Tumora de comportament incert, nespecificata" },

  // ─── D50–D89  Boli ale sangelui ─────────────────────────────────────────
  { code: "D50.0", description: "Anemia feripriva prin pierdere de sange (cronica)" },
  { code: "D50.9", description: "Anemia feripriva, nespecificata" },
  { code: "D51.9", description: "Anemia prin deficit de vitamina B12, nespecificata" },
  { code: "D52.9", description: "Anemia prin deficit de folat, nespecificata" },
  { code: "D55.9", description: "Anemia datorata tulburarilor enzimatice, nespecificata" },
  { code: "D56.9", description: "Talasemia, nespecificata" },
  { code: "D57.1", description: "Anemia drepanocitara fara criza" },
  { code: "D59.9", description: "Anemia hemolitica dobandita, nespecificata" },
  { code: "D60.9", description: "Aplazia eritrocitara pura dobandita, nespecificata" },
  { code: "D61.9", description: "Anemia aplastica, nespecificata" },
  { code: "D62",   description: "Anemia posthemoragica acuta" },
  { code: "D64.9", description: "Anemia, nespecificata" },
  { code: "D69.3", description: "Purpura trombocitopenica idiopatica" },
  { code: "D69.6", description: "Trombocitopenia, nespecificata" },
  { code: "D72.1", description: "Eozinofilia" },
  { code: "D80.9", description: "Imunodeficienta cu predominanta anomaliilor anticorpilor, nespecificata" },

  // ─── E00–E89  Boli endocrine, nutritie si metabolism ────────────────────
  { code: "E01.2", description: "Hipotiroidia iodopriva, nespecificata" },
  { code: "E03.9", description: "Hipotiroidia, nespecificata" },
  { code: "E04.0", description: "Gusa netoxica difuza" },
  { code: "E04.2", description: "Gusa netoxica multinodulara" },
  { code: "E04.9", description: "Gusa netoxica, nespecificata" },
  { code: "E05.0", description: "Tireotoxicoza cu gusa difuza" },
  { code: "E05.9", description: "Tireotoxicoza, nespecificata" },
  { code: "E06.3", description: "Tiroidita autoimuna" },
  { code: "E06.9", description: "Tiroidita, nespecificata" },
  { code: "E10.1", description: "Diabetul zaharat insulinodependent cu cetoacidoza" },
  { code: "E10.4", description: "Diabetul zaharat insulinodependent cu complicatii neurologice" },
  { code: "E10.5", description: "Diabetul zaharat insulinodependent cu complicatii circulatorie periferica" },
  { code: "E10.9", description: "Diabetul zaharat insulinodependent, fara complicatii" },
  { code: "E11.0", description: "Diabetul zaharat insulinorezistent cu coma" },
  { code: "E11.5", description: "Diabetul zaharat insulinorezistent cu complicatii circulatorie periferica" },
  { code: "E11.9", description: "Diabetul zaharat insulinorezistent, fara complicatii" },
  { code: "E13.9", description: "Alte forme specificate de diabet zaharat, fara complicatii" },
  { code: "E14.9", description: "Diabetul zaharat, nespecificat, fara complicatii" },
  { code: "E20.9", description: "Hipoparatiroidia, nespecificata" },
  { code: "E21.0", description: "Hiperparatiroidia primara" },
  { code: "E21.3", description: "Hiperparatiroidia, nespecificata" },
  { code: "E22.0", description: "Acromegalia si gigantismul hipofizar" },
  { code: "E23.0", description: "Hipopituitarismul" },
  { code: "E24.0", description: "Sindromul Cushing de origine hipofizara" },
  { code: "E27.1", description: "Insuficienta corticosuprarenaliana primara" },
  { code: "E27.4", description: "Alte insuficiente corticosuprarenale si nespecificate" },
  { code: "E28.2", description: "Sindromul ovarelor polichistice" },
  { code: "E40",   description: "Kwashiorkor" },
  { code: "E41",   description: "Marasmul nutritional" },
  { code: "E44.0", description: "Malnutritia proteino-calorica moderata" },
  { code: "E46",   description: "Malnutritia proteino-calorica, nespecificata" },
  { code: "E50.9", description: "Deficienta de vitamina A, nespecificata" },
  { code: "E55.9", description: "Deficienta de vitamina D, nespecificata" },
  { code: "E58",   description: "Deficienta de calciu alimentar" },
  { code: "E61.1", description: "Deficienta de fier" },
  { code: "E63.9", description: "Deficienta nutritionala, nespecificata" },
  { code: "E66.0", description: "Obezitatea prin exces caloric" },
  { code: "E66.9", description: "Obezitatea, nespecificata" },
  { code: "E72.1", description: "Tulburarile metabolismului aminoacizilor cu sulf" },
  { code: "E78.0", description: "Hipercolesterolemia pura" },
  { code: "E78.1", description: "Hipertrigliceridemia pura" },
  { code: "E78.2", description: "Hiperlipidemia mixta" },
  { code: "E78.5", description: "Hiperlipidemia, nespecificata" },
  { code: "E79.0", description: "Hiperuricemia fara semnele gutei sau nefropatiei" },
  { code: "E83.5", description: "Tulburarile metabolismului calciului" },
  { code: "E86",   description: "Depletiea de volum (deshidratarea)" },
  { code: "E87.0", description: "Hiperosmolaritate si hipernatriemie" },
  { code: "E87.1", description: "Hipoosmolaritate si hiponatriemie" },
  { code: "E87.5", description: "Hiperpotasemia" },
  { code: "E87.6", description: "Hipopotasemia" },
  { code: "E88.9", description: "Tulburarea metabolismului, nespecificata" },

  // ─── F00–F99  Tulburari mentale si de comportament ──────────────────────
  { code: "F00.9", description: "Dementa in boala Alzheimer, nespecificata" },
  { code: "F01.9", description: "Dementa vasculara, nespecificata" },
  { code: "F02.3", description: "Dementa in boala Parkinson" },
  { code: "F03",   description: "Dementa, nespecificata" },
  { code: "F05.9", description: "Delirul, nespecificat" },
  { code: "F10.0", description: "Tulburari mentale si de comportament datorate consumului de alcool: intoxicatia acuta" },
  { code: "F10.1", description: "Tulburari mentale si de comportament datorate consumului de alcool: uz nociv" },
  { code: "F10.2", description: "Tulburari mentale si de comportament datorate consumului de alcool: sindromul de dependenta" },
  { code: "F10.3", description: "Tulburari mentale datorate consumului de alcool: sindromul de sevraj" },
  { code: "F11.2", description: "Tulburari datorate consumului de opioide: sindromul de dependenta" },
  { code: "F19.2", description: "Tulburari datorate consumului de substante multiple: sindromul de dependenta" },
  { code: "F20.0", description: "Schizofrenia paranoida" },
  { code: "F20.9", description: "Schizofrenia, nespecificata" },
  { code: "F25.9", description: "Tulburarea schizoafectiva, nespecificata" },
  { code: "F29",   description: "Psihoza neorganica, nespecificata" },
  { code: "F31.9", description: "Tulburarea afectiva bipolara, nespecificata" },
  { code: "F32.0", description: "Episodul depresiv usor" },
  { code: "F32.1", description: "Episodul depresiv moderat" },
  { code: "F32.2", description: "Episodul depresiv sever, fara simptome psihotice" },
  { code: "F32.9", description: "Episodul depresiv, nespecificat" },
  { code: "F33.9", description: "Tulburarea depresiva recurenta, nespecificata" },
  { code: "F40.0", description: "Agorafobia" },
  { code: "F40.1", description: "Fobiile sociale" },
  { code: "F41.0", description: "Tulburarea cu atacuri de panica" },
  { code: "F41.1", description: "Tulburarea anxioasa generalizata" },
  { code: "F41.9", description: "Tulburarea anxioasa, nespecificata" },
  { code: "F42.9", description: "Tulburarea obsesiv-compulsiva, nespecificata" },
  { code: "F43.1", description: "Tulburarea de stres posttraumatic" },
  { code: "F43.2", description: "Tulburarile de adaptare" },
  { code: "F44.9", description: "Tulburarea disociativa (de conversie), nespecificata" },
  { code: "F45.9", description: "Tulburarea somatoforma, nespecificata" },
  { code: "F50.0", description: "Anorexia nervoasa" },
  { code: "F50.2", description: "Bulimia nervoasa" },
  { code: "F51.0", description: "Insomnia neorganica" },
  { code: "F60.3", description: "Tulburarea de personalitate borderline" },
  { code: "F60.9", description: "Tulburarea de personalitate, nespecificata" },
  { code: "F70.9", description: "Retardul mintal usor, fara precizarea tulburarilor de comportament" },
  { code: "F84.0", description: "Autismul infantil" },
  { code: "F90.0", description: "Tulburari de activitate si atentie" },
  { code: "F91.9", description: "Tulburarea de conduita, nespecificata" },
  { code: "F99",   description: "Tulburare mentala, nespecificata" },

  // ─── G00–G99  Bolile sistemului nervos ───────────────────────────────────
  { code: "G00.9", description: "Meningita bacteriana, nespecificata" },
  { code: "G03.9", description: "Meningita, nespecificata" },
  { code: "G04.9", description: "Encefalita, mielita si encefalomielita, nespecificata" },
  { code: "G20",   description: "Boala Parkinson" },
  { code: "G30.0", description: "Boala Alzheimer cu debut precoce" },
  { code: "G30.1", description: "Boala Alzheimer cu debut tardiv" },
  { code: "G30.9", description: "Boala Alzheimer, nespecificata" },
  { code: "G35",   description: "Scleroza multipla" },
  { code: "G40.0", description: "Epilepsia idiopatica localizata cu crize focale" },
  { code: "G40.3", description: "Epilepsia idiopatica generalizata" },
  { code: "G40.9", description: "Epilepsia, nespecificata" },
  { code: "G43.0", description: "Migrena fara aura [migrena simpla]" },
  { code: "G43.1", description: "Migrena cu aura [migrena clasica]" },
  { code: "G43.9", description: "Migrena, nespecificata" },
  { code: "G44.2", description: "Cefalee tensionala" },
  { code: "G45.9", description: "Accidentul ischemic tranzitor, nespecificat" },
  { code: "G47.0", description: "Tulburari de adormire si mentinere a somnului [Insomnii]" },
  { code: "G47.3", description: "Apneea de somn" },
  { code: "G51.0", description: "Paralizia Bell" },
  { code: "G54.2", description: "Leziunile radacinilor nervoase cervicale" },
  { code: "G54.4", description: "Leziunile radacinilor nervoase lombare" },
  { code: "G55.0", description: "Compresia radacinilor si plexurilor nervoase in neoplasme" },
  { code: "G56.0", description: "Sindromul de tunel carpian" },
  { code: "G61.0", description: "Sindromul Guillain-Barre" },
  { code: "G62.9", description: "Polineuropatia, nespecificata" },
  { code: "G63.2", description: "Polineuropatia diabetica" },
  { code: "G70.0", description: "Miastenia gravis" },
  { code: "G80.9", description: "Paralizia cerebrala, nespecificata" },

  // ─── H00–H59  Bolile ochiului ────────────────────────────────────────────
  { code: "H00.0", description: "Hordeolul" },
  { code: "H01.0", description: "Blefarita" },
  { code: "H04.3", description: "Inflamatia acuta si nespecificata a aparatului lacrimal" },
  { code: "H10.9", description: "Conjunctivita, nespecificata" },
  { code: "H16.9", description: "Keratita, nespecificata" },
  { code: "H25.9", description: "Cataracta senila, nespecificata" },
  { code: "H26.9", description: "Cataracta, nespecificata" },
  { code: "H33.0", description: "Dezlipirea de retina cu ruptura" },
  { code: "H35.3", description: "Degenerescenta maculara si a polului posterior" },
  { code: "H36.0", description: "Retinopatia diabetica" },
  { code: "H40.9", description: "Glaucomul, nespecificat" },
  { code: "H43.1", description: "Pneumatoftalm (Vitreul fluid)" },
  { code: "H52.1", description: "Miopia" },
  { code: "H52.4", description: "Presbiopia" },
  { code: "H54.0", description: "Orbirea binoculara" },

  // ─── H60–H95  Bolile urechii ─────────────────────────────────────────────
  { code: "H60.9", description: "Otita externa, nespecificata" },
  { code: "H65.9", description: "Otita medie secretorie, nespecificata" },
  { code: "H66.0", description: "Otita medie supurata acuta" },
  { code: "H66.9", description: "Otita medie supurata, nespecificata" },
  { code: "H72.9", description: "Perforatia membranei timpanice, nespecificata" },
  { code: "H81.0", description: "Boala Meniere" },
  { code: "H81.3", description: "Alte vertije periferice" },
  { code: "H83.3", description: "Efectele zgomotelor asupra urechii interne" },
  { code: "H90.3", description: "Surditatea de perceptie bilaterala" },
  { code: "H91.9", description: "Pierderea de auz, nespecificata" },
  { code: "H93.1", description: "Tinitus (Tiuit in urechi)" },

  // ─── I00–I99  Bolile aparatului circulator ───────────────────────────────
  { code: "I05.9", description: "Boala reumatica a valvei mitrale, nespecificata" },
  { code: "I06.9", description: "Boala reumatica a valvei aortice, nespecificata" },
  { code: "I09.9", description: "Boala reumatica de inima, nespecificata" },
  { code: "I10",   description: "Hipertensiunea esentiala (primara)" },
  { code: "I11.0", description: "Boala hipertensiva cardiaca cu insuficienta cardiaca (congestiva)" },
  { code: "I11.9", description: "Boala hipertensiva cardiaca fara insuficienta cardiaca (congestiva)" },
  { code: "I12.9", description: "Boala hipertensiva renala fara insuficienta renala cronica" },
  { code: "I13.1", description: "Boala hipertensiva cu insuficienta renala" },
  { code: "I20.0", description: "Angina pectoris instabila" },
  { code: "I20.9", description: "Angina pectoris, nespecificata" },
  { code: "I21.0", description: "Infarctul miocardic acut transmural al peretelui anterior" },
  { code: "I21.1", description: "Infarctul miocardic acut transmural al peretelui inferior" },
  { code: "I21.4", description: "Infarctul miocardic acut subendocardic" },
  { code: "I21.9", description: "Infarctul miocardic acut, nespecificat" },
  { code: "I22.9", description: "Infarctul miocardic recurent, nespecificat" },
  { code: "I25.1", description: "Boala coronariana aterosclerotica a inimii" },
  { code: "I25.2", description: "Infarctul miocardic vechi" },
  { code: "I25.9", description: "Boala cronica ischemica a inimii, nespecificata" },
  { code: "I26.9", description: "Embolia pulmonara fara mentionarea insuficientei cardiace acute" },
  { code: "I27.0", description: "Hipertensiunea pulmonara primara" },
  { code: "I27.9", description: "Boala cardiaca pulmonara, nespecificata" },
  { code: "I30.9", description: "Pericardita acuta, nespecificata" },
  { code: "I33.0", description: "Endocardita infectioasa acuta si subacuta" },
  { code: "I34.0", description: "Insuficienta valvei mitrale" },
  { code: "I35.0", description: "Stenoza valvei aortice" },
  { code: "I35.1", description: "Insuficienta valvei aortice" },
  { code: "I38",   description: "Endocardita, valvula nespecificata" },
  { code: "I42.0", description: "Cardiomiopatia dilatativa" },
  { code: "I42.9", description: "Cardiomiopatia, nespecificata" },
  { code: "I44.2", description: "Blocul atrioventricular complet" },
  { code: "I45.9", description: "Tulburarea de conducere, nespecificata" },
  { code: "I47.1", description: "Tahicardia supraventriculara" },
  { code: "I47.2", description: "Tahicardia ventriculara" },
  { code: "I48",   description: "Fibrilatia si flutterul atrial" },
  { code: "I49.9", description: "Aritmia cardiaca, nespecificata" },
  { code: "I50.0", description: "Insuficienta cardiaca congestiva" },
  { code: "I50.1", description: "Insuficienta ventriculara stanga" },
  { code: "I50.9", description: "Insuficienta cardiaca, nespecificata" },
  { code: "I51.9", description: "Boala de inima, nespecificata" },
  { code: "I60.9", description: "Hemoragia subarahnoidiana, nespecificata" },
  { code: "I61.9", description: "Hemoragia intracerebrala, nespecificata" },
  { code: "I63.5", description: "Infarctul cerebral datorat ocluziei si stenozei arterelor cerebrale" },
  { code: "I63.9", description: "Infarctul cerebral, nespecificat" },
  { code: "I64",   description: "Accidentul vascular cerebral, nespecificat" },
  { code: "I67.9", description: "Boala cerebrovasculara, nespecificata" },
  { code: "I69.3", description: "Sechele ale infarctului cerebral" },
  { code: "I70.0", description: "Ateroscleroza aortei" },
  { code: "I70.2", description: "Ateroscleroza arterelor extremitatilor" },
  { code: "I70.9", description: "Ateroscleroza generalizata si nespecificata" },
  { code: "I71.4", description: "Anevrismul abdominal al aortei fara mentionarea rupturii" },
  { code: "I71.9", description: "Anevrismul aortei, nespecificat" },
  { code: "I73.9", description: "Boala vasculara periferica, nespecificata" },
  { code: "I74.3", description: "Embolia si tromboza arterelor extremitatilor inferioare" },
  { code: "I80.1", description: "Flebita si tromboflebita venei femurale" },
  { code: "I80.2", description: "Flebita si tromboflebita altor vene profunde ale extremitatilor inferioare" },
  { code: "I80.3", description: "Flebita si tromboflebita extremitatilor inferioare, nespecificata" },
  { code: "I82.9", description: "Embolia si tromboza venoasa, nespecificata" },
  { code: "I83.9", description: "Varicele extremitatilor inferioare, fara ulceratie sau inflamatie" },
  { code: "I84.9", description: "Hemoroizii nespecificati, fara complicatii" },
  { code: "I87.2", description: "Insuficienta venoasa (cronica) (periferica)" },
  { code: "I95.1", description: "Hipotensiunea ortostatica" },
  { code: "I95.9", description: "Hipotensiunea, nespecificata" },

  // ─── J00–J99  Bolile aparatului respirator ───────────────────────────────
  { code: "J00",   description: "Rinofaringita acuta (guturai)" },
  { code: "J01.0", description: "Sinuzita maxilara acuta" },
  { code: "J01.1", description: "Sinuzita frontala acuta" },
  { code: "J01.9", description: "Sinuzita acuta, nespecificata" },
  { code: "J02.0", description: "Faringita streptococica" },
  { code: "J02.9", description: "Faringita acuta, nespecificata" },
  { code: "J03.0", description: "Amigdalita streptococica" },
  { code: "J03.9", description: "Amigdalita acuta, nespecificata" },
  { code: "J04.0", description: "Laringita acuta" },
  { code: "J04.1", description: "Traheita acuta" },
  { code: "J05.1", description: "Epiglotita acuta" },
  { code: "J06.9", description: "Infectia acuta a cailor respiratorii superioare, nespecificata" },
  { code: "J09",   description: "Gripa cu virusuri gripale identificate" },
  { code: "J10.0", description: "Gripa cu pneumonie, virusul gripal identificat" },
  { code: "J10.1", description: "Gripa cu alte manifestari respiratorii, virusul gripal identificat" },
  { code: "J11.0", description: "Gripa cu pneumonie, virusul neidentificat" },
  { code: "J11.1", description: "Gripa cu alte manifestari respiratorii, virusul neidentificat" },
  { code: "J12.9", description: "Pneumonia virala, nespecificata" },
  { code: "J13",   description: "Pneumonia cu streptococcus pneumoniae" },
  { code: "J14",   description: "Pneumonia cu haemophilus influenzae" },
  { code: "J15.0", description: "Pneumonia cu klebsiella pneumoniae" },
  { code: "J15.1", description: "Pneumonia cu pseudomonas" },
  { code: "J15.7", description: "Pneumonia cu mycoplasma pneumoniae" },
  { code: "J15.9", description: "Pneumonia bacteriana, nespecificata" },
  { code: "J18.0", description: "Bronhopneumonia, nespecificata" },
  { code: "J18.1", description: "Pneumonia lobara, nespecificata" },
  { code: "J18.9", description: "Pneumonia, nespecificata" },
  { code: "J20.0", description: "Bronsita acuta datorata mycoplasma pneumoniae" },
  { code: "J20.9", description: "Bronsita acuta, nespecificata" },
  { code: "J21.9", description: "Bronsiolita acuta, nespecificata" },
  { code: "J22",   description: "Infectia acuta nespecificata a cailor respiratorii inferioare" },
  { code: "J30.0", description: "Rinita vasomotorie" },
  { code: "J30.1", description: "Rinita alergica datorata polenului" },
  { code: "J30.4", description: "Rinita alergica cronica" },
  { code: "J31.0", description: "Rinita cronica" },
  { code: "J32.0", description: "Sinuzita maxilara cronica" },
  { code: "J32.9", description: "Sinuzita cronica, nespecificata" },
  { code: "J33.9", description: "Polipul nasal, nespecificat" },
  { code: "J35.0", description: "Amigdalita cronica" },
  { code: "J35.3", description: "Hipertrofia amigdalelor cu hipertrofia vegetatiilor adenoide" },
  { code: "J37.0", description: "Laringita cronica" },
  { code: "J38.3", description: "Alte boli ale corzilor vocale" },
  { code: "J40",   description: "Bronsita, nespecificata ca acuta sau cronica" },
  { code: "J41.0", description: "Bronsita cronica simpla" },
  { code: "J42",   description: "Bronsita cronica nespecificata" },
  { code: "J43.9", description: "Emfizemul, nespecificat" },
  { code: "J44.0", description: "Bronhopneumopatia obstructiva cronica cu infectie respiratorie acuta a cailor inferioare" },
  { code: "J44.1", description: "Bronhopneumopatia obstructiva cronica cu exacerbare acuta" },
  { code: "J44.9", description: "Bronhopneumopatia obstructiva cronica, nespecificata" },
  { code: "J45.0", description: "Astmul predominant alergic" },
  { code: "J45.1", description: "Astmul nealergic" },
  { code: "J45.8", description: "Astmul mixt" },
  { code: "J45.9", description: "Astmul, nespecificat" },
  { code: "J46",   description: "Starea de rau astmatic" },
  { code: "J47",   description: "Bronsiectazia" },
  { code: "J60",   description: "Pneumoconioza minerilor din carbune" },
  { code: "J68.0", description: "Bronsita si pneumonita datorita substantelor chimice, gazelor, fumului" },
  { code: "J70.0", description: "Manifestarile pulmonare acute datorate radiatiilor" },
  { code: "J80",   description: "Sindromul detresei respiratorii al adultului" },
  { code: "J81",   description: "Edemul pulmonar" },
  { code: "J85.1", description: "Abcesul pulmonar cu pneumonie" },
  { code: "J85.2", description: "Abcesul pulmonar fara pneumonie" },
  { code: "J86.9", description: "Pleurezia purulenta, nespecificata" },
  { code: "J90",   description: "Revarsatul pleural" },
  { code: "J93.9", description: "Pneumotoracele, nespecificat" },
  { code: "J96.0", description: "Insuficienta respiratorie acuta" },
  { code: "J96.1", description: "Insuficienta respiratorie cronica" },
  { code: "J96.9", description: "Insuficienta respiratorie, nespecificata" },
  { code: "J98.1", description: "Colapsul pulmonar" },

  // ─── K00–K93  Bolile aparatului digestiv ─────────────────────────────────
  { code: "K00.6", description: "Tulburarile de eruptie dentara" },
  { code: "K02.9", description: "Caria dentara, nespecificata" },
  { code: "K05.1", description: "Gingivita cronica" },
  { code: "K08.1", description: "Pierderea dentara datorata unui accident, extractiei sau afectiunii locale" },
  { code: "K11.2", description: "Sialadenitele" },
  { code: "K12.0", description: "Stomatita aftoasa recurenta" },
  { code: "K12.1", description: "Alte forme de stomatita" },
  { code: "K13.0", description: "Bolile buzelor" },
  { code: "K20",   description: "Esofagita" },
  { code: "K21.0", description: "Boala de reflux gastroesofagian cu esofagita" },
  { code: "K21.9", description: "Boala de reflux gastroesofagian fara esofagita" },
  { code: "K22.2", description: "Ulcerul esofagian" },
  { code: "K25.0", description: "Ulcerul gastric acut cu hemoragie" },
  { code: "K25.9", description: "Ulcerul gastric, nespecificat" },
  { code: "K26.0", description: "Ulcerul duodenal acut cu hemoragie" },
  { code: "K26.9", description: "Ulcerul duodenal, nespecificat" },
  { code: "K27.9", description: "Ulcerul peptic, nespecificat" },
  { code: "K29.0", description: "Gastrita hemoragica acuta" },
  { code: "K29.5", description: "Gastrita cronica, nespecificata" },
  { code: "K29.7", description: "Gastrita, nespecificata" },
  { code: "K30",   description: "Dispepsia functionala" },
  { code: "K35.8", description: "Apendicita acuta cu alte complicatii" },
  { code: "K37",   description: "Apendicita, nespecificata" },
  { code: "K38.2", description: "Diverticulul apendicular" },
  { code: "K40.9", description: "Hernia inghinala unilaterala sau nespecificata, fara obstructie sau gangrena" },
  { code: "K41.9", description: "Hernia crurala unilaterala sau nespecificata, fara obstructie sau gangrena" },
  { code: "K43.9", description: "Hernia ventrala, fara obstructie sau gangrena" },
  { code: "K44.9", description: "Hernia diafragmatica, fara obstructie sau gangrena" },
  { code: "K46.9", description: "Hernia abdominala nespecificata, fara obstructie sau gangrena" },
  { code: "K50.0", description: "Boala Crohn a intestinului subtire" },
  { code: "K50.1", description: "Boala Crohn a intestinului gros" },
  { code: "K50.9", description: "Boala Crohn, nespecificata" },
  { code: "K51.0", description: "Colita ulceroasa (cronica) panhocolita" },
  { code: "K51.9", description: "Colita ulceroasa, nespecificata" },
  { code: "K52.9", description: "Gastroenterita si colita neinfectioasa, nespecificata" },
  { code: "K55.0", description: "Bolile vasculare acute ale intestinului" },
  { code: "K56.6", description: "Alte obstructii intestinale si nespecificate" },
  { code: "K57.3", description: "Boala diverticulara a intestinului gros fara perforatie sau abces" },
  { code: "K57.9", description: "Boala diverticulara a intestinului, nespecificata" },
  { code: "K59.0", description: "Constipatia" },
  { code: "K59.1", description: "Diareea functionala" },
  { code: "K62.5", description: "Hemoragia anala si rectala" },
  { code: "K63.5", description: "Polipul colonului" },
  { code: "K70.0", description: "Ficatul alcoolic gras" },
  { code: "K70.3", description: "Ciroza hepatica alcoolica" },
  { code: "K70.9", description: "Boala hepatica alcoolica, nespecificata" },
  { code: "K72.0", description: "Insuficienta hepatica acuta si subacuta" },
  { code: "K72.9", description: "Insuficienta hepatica, nespecificata" },
  { code: "K73.9", description: "Hepatita cronica, nespecificata" },
  { code: "K74.6", description: "Ciroza hepatica, nespecificata" },
  { code: "K75.9", description: "Boala inflamatorie a ficatului, nespecificata" },
  { code: "K76.0", description: "Degenerescenta grasa a ficatului" },
  { code: "K76.9", description: "Boala ficatului, nespecificata" },
  { code: "K80.1", description: "Calculii vezicii biliare cu alta colecistita" },
  { code: "K80.2", description: "Calculii vezicii biliare fara colecistita" },
  { code: "K80.5", description: "Calculii cailor biliare fara colangita sau colecistita" },
  { code: "K80.9", description: "Colelitiaza, nespecificata" },
  { code: "K81.0", description: "Colecistita acuta" },
  { code: "K81.1", description: "Colecistita cronica" },
  { code: "K81.9", description: "Colecistita, nespecificata" },
  { code: "K82.9", description: "Boala vezicii biliare, nespecificata" },
  { code: "K83.9", description: "Boala cailor biliare, nespecificata" },
  { code: "K85.9", description: "Pancreatita acuta, nespecificata" },
  { code: "K86.1", description: "Alte forme de pancreatita cronica" },
  { code: "K86.9", description: "Boala pancreasului, nespecificata" },
  { code: "K92.0", description: "Hematemeza" },
  { code: "K92.1", description: "Melena" },
  { code: "K92.9", description: "Boala tractului digestiv, nespecificata" },

  // ─── L00–L99  Bolile pielii ──────────────────────────────────────────────
  { code: "L00",   description: "Sindromul stafilococic al pielii oparite" },
  { code: "L01.0", description: "Impetigo [orice localizare, orice organism]" },
  { code: "L02.9", description: "Abcesul cutanat, furunchei si carbunchii, nespecificata" },
  { code: "L03.9", description: "Celulita, nespecificata" },
  { code: "L08.9", description: "Infectia locala a pielii si tesutului subcutanat, nespecificata" },
  { code: "L10.0", description: "Pemfigus vulgar" },
  { code: "L13.0", description: "Dermatita herpetiformis" },
  { code: "L20.9", description: "Dermatita atopica, nespecificata" },
  { code: "L21.9", description: "Dermatita seboreica, nespecificata" },
  { code: "L23.9", description: "Dermatita de contact alergica, nespecificata" },
  { code: "L24.9", description: "Dermatita de contact iritativa, nespecificata" },
  { code: "L25.9", description: "Dermatita de contact, nespecificata" },
  { code: "L27.0", description: "Eruptia generalizata a pielii datorata medicamentelor" },
  { code: "L29.9", description: "Pruritul, nespecificat" },
  { code: "L30.9", description: "Dermatita, nespecificata" },
  { code: "L40.0", description: "Psoriazisul vulgar" },
  { code: "L40.9", description: "Psoriazisul, nespecificat" },
  { code: "L41.9", description: "Parapsoriazisul, nespecificat" },
  { code: "L43.9", description: "Lichenul plan, nespecificat" },
  { code: "L50.0", description: "Urticaria alergica" },
  { code: "L50.9", description: "Urticaria, nespecificata" },
  { code: "L51.9", description: "Eritemul exudativ multiform, nespecificat" },
  { code: "L52",   description: "Eritemul nodos" },
  { code: "L57.0", description: "Cheratoze actinice" },
  { code: "L60.0", description: "Unghia incarnata" },
  { code: "L70.0", description: "Acneea vulgara" },
  { code: "L72.0", description: "Chistul folicular" },
  { code: "L80",   description: "Vitiligo" },
  { code: "L81.1", description: "Chloasma" },
  { code: "L89.9", description: "Ulcerul de decubit, nespecificat" },
  { code: "L90.0", description: "Lichenul scleros si atrofic" },
  { code: "L92.0", description: "Granulomul inelar" },
  { code: "L98.4", description: "Ulcerul cronic al pielii, neclasificat altundeva" },

  // ─── M00–M99  Bolile sistemului osteoarticular ───────────────────────────
  { code: "M00.9", description: "Artrita infectioasa, nespecificata" },
  { code: "M05.0", description: "Sindromul Felty" },
  { code: "M05.9", description: "Artrita reumatoida seropozitiva, nespecificata" },
  { code: "M06.0", description: "Artrita reumatoida seronegativa" },
  { code: "M06.9", description: "Artrita reumatoida, nespecificata" },
  { code: "M08.9", description: "Artrita juvenila, nespecificata" },
  { code: "M10.0", description: "Guta idiopatica" },
  { code: "M10.9", description: "Guta, nespecificata" },
  { code: "M13.9", description: "Artrita, nespecificata" },
  { code: "M15.9", description: "Poliartroza, nespecificata" },
  { code: "M16.1", description: "Coxartroza primara unilaterala" },
  { code: "M16.9", description: "Coxartroza, nespecificata" },
  { code: "M17.1", description: "Gonartroza primara unilaterala" },
  { code: "M17.9", description: "Gonartroza, nespecificata" },
  { code: "M19.9", description: "Artroza, nespecificata" },
  { code: "M25.5", description: "Durerea articulara" },
  { code: "M32.9", description: "Lupus eritematos sistemic, nespecificat" },
  { code: "M33.2", description: "Polimiozita" },
  { code: "M34.9", description: "Sclerodermia, nespecificata" },
  { code: "M35.0", description: "Sindromul Sjögren" },
  { code: "M42.1", description: "Osteocondrita coloanei vertebrale la adult" },
  { code: "M45",   description: "Spondilita anchilozanta" },
  { code: "M47.8", description: "Alte spondilartroze" },
  { code: "M47.9", description: "Spondiloza, nespecificata" },
  { code: "M48.0", description: "Stenoza canalului vertebral" },
  { code: "M50.1", description: "Boala discului cervical cu radiculopatie" },
  { code: "M51.1", description: "Radiculopatia lombara si lombosacrata" },
  { code: "M51.9", description: "Boala discului intervertebral, nespecificata" },
  { code: "M54.2", description: "Cervicalgia" },
  { code: "M54.4", description: "Lumbosacralgia" },
  { code: "M54.5", description: "Lombodinia" },
  { code: "M65.9", description: "Sinovita si tendosinovita, nespecificata" },
  { code: "M71.3", description: "Alte bursite ale genunchiului" },
  { code: "M75.1", description: "Sindromul mansonului rotatorilor" },
  { code: "M76.6", description: "Tendinita achiliana" },
  { code: "M77.0", description: "Epicondilita mediala" },
  { code: "M77.1", description: "Epicondilita laterala (cot de tenis)" },
  { code: "M79.3", description: "Panniculita" },
  { code: "M79.7", description: "Fibromialgia" },
  { code: "M80.9", description: "Osteoporoza cu fractura de fragilitate, nespecificata" },
  { code: "M81.0", description: "Osteoporoza postmenopauza" },
  { code: "M81.9", description: "Osteoporoza, nespecificata" },
  { code: "M84.4", description: "Fractura de stres" },
  { code: "M85.8", description: "Alte tulburari ale densitatii osoase si structurii osoase" },

  // ─── N00–N99  Bolile aparatului genitourinar ─────────────────────────────
  { code: "N00.9", description: "Sindromul nefritic acut, nespecificat" },
  { code: "N03.9", description: "Sindromul nefritic cronic, nespecificat" },
  { code: "N04.9", description: "Sindromul nefrotic, nespecificat" },
  { code: "N05.9", description: "Sindromul nefritic nespecificat, nespecificat" },
  { code: "N10",   description: "Nefrita tubulointersticiala acuta" },
  { code: "N11.9", description: "Nefrita tubulointersticiala cronica, nespecificata" },
  { code: "N12",   description: "Nefrita tubulointersticiala, nespecificata ca acuta sau cronica" },
  { code: "N17.9", description: "Insuficienta renala acuta, nespecificata" },
  { code: "N18.1", description: "Boala renala cronica, stadiul 1" },
  { code: "N18.3", description: "Boala renala cronica, stadiul 3" },
  { code: "N18.5", description: "Boala renala cronica, stadiul 5" },
  { code: "N18.9", description: "Boala renala cronica, nespecificata" },
  { code: "N19",   description: "Insuficienta renala, nespecificata" },
  { code: "N20.0", description: "Calculul renal" },
  { code: "N20.1", description: "Calculul ureteral" },
  { code: "N20.9", description: "Calculul urinar, nespecificat" },
  { code: "N23",   description: "Colica renala, nespecificata" },
  { code: "N28.9", description: "Boala rinichiului si ureterului, nespecificata" },
  { code: "N30.0", description: "Cistita acuta" },
  { code: "N30.1", description: "Cistita interstitiala (cronica)" },
  { code: "N30.9", description: "Cistita, nespecificata" },
  { code: "N34.1", description: "Uretrita nespecifica" },
  { code: "N35.9", description: "Strictura uretrei, nespecificata" },
  { code: "N39.0", description: "Infectia tractului urinar, fara precizarea sediului" },
  { code: "N40",   description: "Hiperplazia benigna a prostatei" },
  { code: "N41.0", description: "Prostatita acuta" },
  { code: "N41.1", description: "Prostatita cronica" },
  { code: "N45.9", description: "Orhita, epididimita si vasaepididimita, nespecificata" },
  { code: "N48.1", description: "Fimoza" },
  { code: "N60.9", description: "Displazia mamara benigna, nespecificata" },
  { code: "N63",   description: "Masa mamara nediferntiata" },
  { code: "N70.0", description: "Salpingita acuta si ovarita acuta" },
  { code: "N70.9", description: "Salpingita si ovarita, nespecificata" },
  { code: "N71.9", description: "Boala inflamatorie a uterului, nespecificata" },
  { code: "N72",   description: "Bolile inflamatorii ale colului uterin" },
  { code: "N73.9", description: "Boala inflamatorie pelviana feminina, nespecificata" },
  { code: "N76.0", description: "Vaginita acuta" },
  { code: "N76.1", description: "Vaginita subacuta si cronica" },
  { code: "N80.0", description: "Endometrioza uterina" },
  { code: "N80.9", description: "Endometrioza, nespecificata" },
  { code: "N83.2", description: "Alte chisturi ovariene si nespecificate" },
  { code: "N84.0", description: "Polipul corpului uterin" },
  { code: "N85.0", description: "Hiperplazia glandulara a endometrului" },
  { code: "N91.2", description: "Amenoreea, nespecificata" },
  { code: "N92.0", description: "Menstruatia abundenta si frecventa cu ciclu regulat" },
  { code: "N92.6", description: "Menstruatia neregulata, nespecificata" },
  { code: "N93.9", description: "Hemoragia uterina sau vaginala anormala, nespecificata" },
  { code: "N94.1", description: "Dispareunie" },
  { code: "N95.1", description: "Starea de menopauza si climacterica a femeii" },
  { code: "N97.9", description: "Infertilitatea feminina, nespecificata" },

  // ─── O00–O99  Sarcina, nasterea si lauzia ────────────────────────────────
  { code: "O03.9", description: "Avortul spontan, complet sau nespecificat" },
  { code: "O10.0", description: "Hipertensiunea esentiala preexistenta ce complica sarcina" },
  { code: "O13",   description: "Hipertensiunea gestationala [indusa de sarcina]" },
  { code: "O14.1", description: "Preeclampsia severa" },
  { code: "O15.9", description: "Eclampsia, nespecificata" },
  { code: "O20.0", description: "Amenintare de avort" },
  { code: "O21.0", description: "Hiperemezia gravidica usoara" },
  { code: "O26.6", description: "Leziunea ficatului in cursul sarcinii, nasterii si lauziei" },
  { code: "O34.2", description: "Asistenta acordata mamei pentru cicatrice uterina datorata operatiei cezariene" },
  { code: "O42.9", description: "Ruptura prematura a membranelor, nespecificata" },
  { code: "O60.1", description: "Travaliul prematur cu nastere prematura" },
  { code: "O62.1", description: "Contractiile uterine secundare" },
  { code: "O72.1", description: "Alte hemoragii postpartum imediate" },
  { code: "O80",   description: "Nasterea prin prezentatie craniana" },
  { code: "O82",   description: "Nasterea prin operatie cezariana" },
  { code: "O85",   description: "Sepsis puerperal" },
  { code: "O90.3", description: "Cardiomiopatia puerperala" },

  // ─── Q00–Q99  Malformatii congenitale ────────────────────────────────────
  { code: "Q21.0", description: "Defectul de sept ventricular" },
  { code: "Q21.1", description: "Defectul de sept atrial" },
  { code: "Q23.0", description: "Stenoza congenitala a valvei aortice" },
  { code: "Q25.0", description: "Persistenta canalului arterial" },
  { code: "Q35.9", description: "Palatoschizisul, nespecificat" },
  { code: "Q90.9", description: "Trisomia 21, nespecificata" },

  // ─── R00–R99  Simptome si semne ──────────────────────────────────────────
  { code: "R00.0", description: "Tahicardia, nespecificata" },
  { code: "R00.1", description: "Bradicardia, nespecificata" },
  { code: "R00.8", description: "Alte tulburari de ritm cardiac si nespecificate" },
  { code: "R01.1", description: "Suflul cardiac, neclasificat altundeva" },
  { code: "R04.2", description: "Hemoptizia" },
  { code: "R05",   description: "Tusea" },
  { code: "R06.0", description: "Dispneea" },
  { code: "R06.2", description: "Wheezing-ul" },
  { code: "R07.0", description: "Durerea in gat" },
  { code: "R07.4", description: "Durerea toracica, nespecificata" },
  { code: "R09.2", description: "Oprirea cardiorespiratorie" },
  { code: "R10.1", description: "Durerea in abdomenul superior" },
  { code: "R10.4", description: "Alte dureri abdominale si cele nespecificate" },
  { code: "R11",   description: "Greata si varsatura" },
  { code: "R13",   description: "Disfagia" },
  { code: "R14",   description: "Flatulenta si afectiunile inrudite" },
  { code: "R15",   description: "Incontinenta fecala" },
  { code: "R17",   description: "Icterul nespecificat" },
  { code: "R19.7", description: "Scaunul anormal" },
  { code: "R20.2", description: "Parestezii cutanate" },
  { code: "R21",   description: "Eruptia cutanata si alte manifestari nespecificate" },
  { code: "R25.2", description: "Crampele si spasmele" },
  { code: "R31",   description: "Hematuria nespecificata" },
  { code: "R32",   description: "Incontinenta urinara nespecificata" },
  { code: "R33",   description: "Retentia urinara" },
  { code: "R35",   description: "Poliuria" },
  { code: "R39.0", description: "Extravasarea urinei" },
  { code: "R41.3", description: "Alte tulburari de memorie" },
  { code: "R42",   description: "Ametelile si starile de instabilitate" },
  { code: "R43.0", description: "Anosmia" },
  { code: "R45.1", description: "Agitatia si nelinistea" },
  { code: "R50.9", description: "Febra, nespecificata" },
  { code: "R51",   description: "Cefaleea" },
  { code: "R52.9", description: "Durerea nespecificata" },
  { code: "R53",   description: "Starea generala de rau si oboseala" },
  { code: "R55",   description: "Sincopa si colapsul" },
  { code: "R56.8", description: "Alte convulsii si nespecificate" },
  { code: "R57.0", description: "Socul cardiogen" },
  { code: "R57.9", description: "Socul, nespecificat" },
  { code: "R58",   description: "Hemoragia, neclasificata altundeva" },
  { code: "R60.9", description: "Edemul, nespecificat" },
  { code: "R63.0", description: "Anorexia" },
  { code: "R63.1", description: "Polidipsia" },
  { code: "R63.4", description: "Scaderea anormala in greutate" },
  { code: "R63.5", description: "Cresterea anormala in greutate" },
  { code: "R65.1", description: "Sindromul de disfunctie organica multipla" },
  { code: "R68.8", description: "Alte simptome si semne generale specificate" },
  { code: "R73.0", description: "Glicemia crescuta" },
  { code: "R73.9", description: "Hiperglicemia, nespecificata" },
  { code: "R74.0", description: "Activitate enzimelor transaminazei crescuta" },
  { code: "R79.0", description: "Anomalii ale proteinelor plasmatice" },

  // ─── S00–T98  Traumatisme si leziuni ─────────────────────────────────────
  { code: "S00.9", description: "Leziunea superficiala a capului, nespecificata" },
  { code: "S06.0", description: "Comotia cerebrala" },
  { code: "S06.9", description: "Leziunea intracraniana, nespecificata" },
  { code: "S09.9", description: "Traumatismul capului, nespecificat" },
  { code: "S12.9", description: "Fractura vertebrei cervicale, nespecificata" },
  { code: "S22.0", description: "Fractura vertebrei toracice" },
  { code: "S22.4", description: "Fracturi multiple ale coastelor" },
  { code: "S30.9", description: "Leziunea superficiala a abdomenului, nespecificata" },
  { code: "S32.0", description: "Fractura vertebrei lombare" },
  { code: "S32.4", description: "Fractura acetabulului" },
  { code: "S32.5", description: "Fractura oaselor pubiene" },
  { code: "S42.0", description: "Fractura claviculei" },
  { code: "S42.2", description: "Fractura extremitatii superioare a humerusului" },
  { code: "S52.5", description: "Fractura extremitatii inferioare a radiusului" },
  { code: "S62.3", description: "Fractura oaselor metacarpiene" },
  { code: "S72.0", description: "Fractura colului femurului" },
  { code: "S72.1", description: "Fractura pertrohanteriana" },
  { code: "S82.1", description: "Fractura extremitatii superioare a tibiei" },
  { code: "S82.6", description: "Fractura maleolei externe" },
  { code: "T39.0", description: "Intoxicatia cu salicilate" },
  { code: "T40.1", description: "Intoxicatia cu heroina" },
  { code: "T45.5", description: "Intoxicatia cu anticoagulante" },
  { code: "T50.9", description: "Intoxicatia cu alte medicamente si substante nespecificate" },
  { code: "T65.9", description: "Efectul toxic al altor substante si substante nespecificate" },
  { code: "T78.0", description: "Soc anafilactic datorat reactiei adverse la aliment" },
  { code: "T78.1", description: "Alte reactii adverse la alimente" },
  { code: "T78.4", description: "Alergia, nespecificata" },

  // ─── Z00–Z99  Factori ce influenteaza starea de sanatate ─────────────────
  { code: "Z00.0", description: "Examen medical general, al persoanei sanatoase" },
  { code: "Z01.0", description: "Examinarea ochilor si vederii" },
  { code: "Z01.1", description: "Examinarea urechilor si auzului" },
  { code: "Z03.0", description: "Observatia pentru tuberculoza suspectata" },
  { code: "Z08.0", description: "Consultatia de control dupa tratamentul chirurgical al tumorilor maligne" },
  { code: "Z09.9", description: "Consultatie de control dupa tratament, nespecificat" },
  { code: "Z11.1", description: "Examinarea de screening pentru tuberculoza" },
  { code: "Z12.1", description: "Examinarea de screening pentru tumoarea maligna a intestinului" },
  { code: "Z12.3", description: "Examinarea de screening pentru tumoarea maligna a colului uterin" },
  { code: "Z12.4", description: "Examinarea de screening pentru tumoarea maligna a colului uterin" },
  { code: "Z13.0", description: "Examinarea de screening pentru anemie" },
  { code: "Z23",   description: "Necesitatea vaccinarii impotriva holerei" },
  { code: "Z30.0", description: "Sfaturi si prescriptii generale referitoare la contraceptie" },
  { code: "Z30.1", description: "Prescrierea contraceptivelor" },
  { code: "Z34.0", description: "Supravegherea unei sarcini normale de prima data" },
  { code: "Z34.9", description: "Supravegherea unei sarcini normale, nespecificata" },
  { code: "Z35.9", description: "Supravegherea unei sarcini cu rise, nespecificata" },
  { code: "Z51.1", description: "Chimioterapie antineoplazica" },
  { code: "Z51.2", description: "Alte chimioterapii" },
  { code: "Z51.5", description: "Ingrijiri paleative" },
  { code: "Z54.0", description: "Convalescenta dupa chirurgie" },
  { code: "Z71.0", description: "Persoana care consulta in numele alteia" },
  { code: "Z72.0", description: "Consumul de tutun" },
  { code: "Z72.1", description: "Consumul de alcool" },
  { code: "Z72.2", description: "Consumul de droguri" },
  { code: "Z74.0", description: "Reducerea mobilitatii" },
  { code: "Z75.0", description: "Lipsa disponibilitatii serviciilor de sanatate" },
  { code: "Z76.2", description: "Consultatie pentru sanatatea sugarului sau copilului" },
  { code: "Z82.4", description: "Antecedente familiale de boli ischemice ale inimii" },
  { code: "Z85.3", description: "Antecedente personale de tumoare maligna a sanului" },
  { code: "Z87.3", description: "Antecedente personale de boli ale sistemului musculoscheletal" },
  { code: "Z91.0", description: "Alergia la alturi decat datorata medicamentelor si substantelor biologice" },
  { code: "Z95.0", description: "Prezenta stimulatorului cardiac" },
  { code: "Z95.1", description: "Prezenta pontajului aortocoronarian" },
  { code: "Z96.4", description: "Prezenta implantelor endovasculare" },
  { code: "Z96.6", description: "Prezenta implantelor articulare ortopedice" },
  { code: "Z99.2", description: "Dependenta de dializa renala" },
];
