import type { Patient, MedicalRecord, LabResult, Note, Appointment, ChatSession } from "./types";

export const MOCK_PATIENTS: Patient[] = [
  {
    id: "p001",
    fullName: "James Harrison",
    dateOfBirth: "1978-04-12",
    sex: "Male",
    nationalId: "NH-78041201",
    phone: "+1 (555) 234-5678",
    email: "james.harrison@email.com",
    bloodType: "O+",
    allergies: "Penicillin, Sulfonamides",
    currentMedications: "Lisinopril 10mg daily, Atorvastatin 20mg",
    createdAt: "2023-01-15T08:00:00Z",
    updatedAt: "2024-11-20T14:30:00Z",
  },
  {
    id: "p002",
    fullName: "Maria Santos",
    dateOfBirth: "1992-09-27",
    sex: "Female",
    nationalId: "NH-92092701",
    phone: "+1 (555) 345-6789",
    email: "maria.santos@email.com",
    bloodType: "A+",
    allergies: "None known",
    currentMedications: "Metformin 500mg twice daily",
    createdAt: "2023-03-20T10:00:00Z",
    updatedAt: "2024-12-01T09:00:00Z",
  },
  {
    id: "p003",
    fullName: "Robert Chen",
    dateOfBirth: "1965-11-03",
    sex: "Male",
    nationalId: "NH-65110301",
    phone: "+1 (555) 456-7890",
    email: "robert.chen@email.com",
    bloodType: "B+",
    allergies: "Aspirin, NSAIDs",
    currentMedications: "Amlodipine 5mg, Omeprazole 20mg",
    createdAt: "2022-07-10T11:00:00Z",
    updatedAt: "2024-10-15T16:00:00Z",
  },
  {
    id: "p004",
    fullName: "Susan Mitchell",
    dateOfBirth: "1985-06-18",
    sex: "Female",
    nationalId: "NH-85061801",
    phone: "+1 (555) 567-8901",
    email: "susan.mitchell@email.com",
    bloodType: "AB+",
    allergies: "Latex, Codeine",
    currentMedications: "Levothyroxine 50mcg",
    createdAt: "2023-06-05T13:00:00Z",
    updatedAt: "2024-11-30T11:00:00Z",
  },
  {
    id: "p005",
    fullName: "David Park",
    dateOfBirth: "1990-02-14",
    sex: "Male",
    nationalId: "NH-90021401",
    phone: "+1 (555) 678-9012",
    email: "david.park@email.com",
    bloodType: "O-",
    allergies: "None known",
    currentMedications: "Albuterol inhaler PRN",
    createdAt: "2024-01-08T09:00:00Z",
    updatedAt: "2024-12-05T10:00:00Z",
  },
  {
    id: "p006",
    fullName: "Linda Johnson",
    dateOfBirth: "1958-07-22",
    sex: "Female",
    nationalId: "NH-58072201",
    phone: "+1 (555) 789-0123",
    email: "linda.johnson@email.com",
    bloodType: "A-",
    allergies: "Shellfish (non-drug allergy)",
    currentMedications: "Metoprolol 25mg, Furosemide 40mg, Warfarin 5mg",
    createdAt: "2022-02-14T07:00:00Z",
    updatedAt: "2024-12-10T08:00:00Z",
  },
];

export const MOCK_MEDICAL_RECORDS: MedicalRecord[] = [
  {
    id: "mr001",
    patientId: "p001",
    date: "2024-11-20",
    doctor: "Dr. Emily Carter",
    visitType: "Emergency",
    chiefComplaint: "Severe right-sided flank pain, blood in urine",
    diagnosis: "Nephrolithiasis (Kidney Stones) — Right ureter",
    icdCode: "N20.1",
    secondaryDiagnoses: "Hypercalciuria, Dehydration",
    symptoms: "Severe flank pain 9/10, hematuria (gross), nausea, vomiting x2. Pain radiating to right groin. Unable to find comfortable position.",
    physicalExam: "CVA tenderness right side ++. Abdomen mildly tender RLQ. No peritoneal signs. Bowel sounds present.",
    vitalSigns: {
      bloodPressure: "148/92",
      heartRate: "104 bpm",
      temperature: "37.2°C",
      respiratoryRate: "18/min",
      oxygenSaturation: "98%",
      weight: "82 kg",
    },
    treatment: "Emergent IV access established. IV hydration initiated. Pain controlled with Ketorolac IV. Tamsulosin started for stone facilitation. Non-contrast CT abdomen/pelvis ordered. Urology on-call notified. Patient monitored for 4 hours in ED before discharge with close outpatient follow-up.",
    prescribedDrugs: [
      {
        id: "d001",
        name: "Ketorolac",
        genericName: "Ketorolac Tromethamine",
        dose: "30mg",
        route: "IV",
        frequency: "Every 6 hours",
        duration: "2 days",
        quantity: "8 vials",
        refills: "No refills",
        instructions: "Administer over 15 seconds. Do not exceed 5 days total therapy.",
        indication: "Acute renal colic pain management",
        startDate: "2024-11-20",
        endDate: "2024-11-22",
        prescribedBy: "Dr. Emily Carter",
      },
      {
        id: "d002",
        name: "Tamsulosin",
        genericName: "Tamsulosin HCl",
        dose: "0.4mg",
        route: "Oral",
        frequency: "Once daily",
        duration: "4 weeks",
        quantity: "28 capsules",
        refills: "1 refill",
        instructions: "Take 30 minutes after the same meal each day. May cause dizziness — avoid driving initially.",
        indication: "Medical expulsive therapy for ureteral stone",
        startDate: "2024-11-20",
        endDate: "2024-12-18",
        prescribedBy: "Dr. Emily Carter",
      },
      {
        id: "d003",
        name: "Ondansetron",
        genericName: "Ondansetron HCl",
        dose: "4mg",
        route: "IV",
        frequency: "Every 8 hours",
        duration: "1 day",
        quantity: "3 vials",
        refills: "No refills",
        instructions: "Administer as needed for nausea/vomiting. Monitor QTc.",
        indication: "Nausea and vomiting associated with renal colic",
        startDate: "2024-11-20",
        endDate: "2024-11-20",
        prescribedBy: "Dr. Emily Carter",
      },
      {
        id: "d004",
        name: "Sodium Chloride 0.9%",
        dose: "1000mL",
        route: "IV",
        frequency: "Once daily",
        duration: "2 days",
        quantity: "2 bags",
        refills: "No refills",
        instructions: "Infuse at 250 mL/hr. Monitor fluid balance.",
        indication: "Rehydration and stone facilitation",
        startDate: "2024-11-20",
        endDate: "2024-11-21",
        prescribedBy: "Dr. Emily Carter",
      },
    ],
    procedures: "Non-contrast CT abdomen/pelvis, IV access x2, Urinalysis with microscopy",
    urgency: "Urgent",
    followUpIn: "1 week",
    followUpType: "Office visit",
    referral: "Urology — Dr. Patterson — within 1 week if stone not passed",
    patientEducation: "Instructed to strain urine to capture stone for analysis. Increase fluid intake to 3L/day. Avoid high-oxalate foods. Return to ED immediately if fever, chills, or worsening pain.",
    attachments: [],
    createdAt: "2024-11-20T14:30:00Z",
  },
  {
    id: "mr002",
    patientId: "p001",
    date: "2024-08-15",
    doctor: "Dr. Emily Carter",
    visitType: "Follow-up",
    chiefComplaint: "Blood pressure follow-up, persistent headaches",
    diagnosis: "Hypertension Stage 1",
    icdCode: "I10",
    symptoms: "Persistent morning headaches, occasional dizziness. BP diary shows consistent readings 140–155/88–95 over 3 weeks.",
    physicalExam: "BP 152/94 right arm, 150/92 left arm. Regular heart sounds. No papilledema. No bruits.",
    vitalSigns: {
      bloodPressure: "152/94",
      heartRate: "78 bpm",
      temperature: "36.8°C",
      oxygenSaturation: "99%",
      weight: "84 kg",
    },
    treatment: "Uptitrated Lisinopril from 5mg to 10mg daily. DASH diet counselling provided. Home BP monitoring reinforced. Stress management discussed. Target BP <130/80.",
    prescribedDrugs: [
      {
        id: "d005",
        name: "Lisinopril",
        dose: "10mg",
        route: "Oral",
        frequency: "Once daily",
        duration: "Ongoing",
        quantity: "90 tablets",
        refills: "3 refills",
        instructions: "Take at the same time each day. Monitor for dry cough. Avoid NSAIDs.",
        indication: "Hypertension — dose uptitration",
        startDate: "2024-08-15",
        prescribedBy: "Dr. Emily Carter",
      },
    ],
    urgency: "Routine",
    followUpIn: "4 weeks",
    followUpType: "Office visit",
    patientEducation: "DASH diet pamphlet provided. Sodium intake <2300mg/day. Avoid NSAIDs — can raise BP and interact with Lisinopril.",
    attachments: [],
    createdAt: "2024-08-15T10:00:00Z",
  },
  {
    id: "mr003",
    patientId: "p002",
    date: "2024-12-01",
    doctor: "Dr. Michael Torres",
    visitType: "Follow-up",
    chiefComplaint: "Routine diabetes management review",
    diagnosis: "Type 2 Diabetes Mellitus — Controlled",
    icdCode: "E11.9",
    symptoms: "No acute symptoms. Reports good dietary compliance. Occasional fatigue. No hypoglycaemic episodes.",
    physicalExam: "Weight stable. No peripheral oedema. Foot examination normal — intact sensation bilaterally.",
    vitalSigns: {
      bloodPressure: "124/78",
      heartRate: "72 bpm",
      temperature: "36.6°C",
      weight: "68 kg",
    },
    treatment: "HbA1c 7.1% — within target. Continue current regimen. Reinforced dietary compliance. Scheduled annual eye exam and microalbumin urine test.",
    prescribedDrugs: [
      {
        id: "d006",
        name: "Metformin",
        genericName: "Metformin Hydrochloride",
        dose: "500mg",
        route: "Oral",
        frequency: "Twice daily",
        duration: "Ongoing",
        quantity: "60 tablets",
        refills: "3 refills",
        instructions: "Take with meals to reduce GI side effects. Hold if contrast imaging scheduled.",
        indication: "Type 2 Diabetes Mellitus — glycaemic control",
        startDate: "2024-12-01",
        prescribedBy: "Dr. Michael Torres",
      },
    ],
    urgency: "Routine",
    followUpIn: "3 months",
    followUpType: "Lab work",
    patientEducation: "Annual eye exam due. Urine microalbumin test ordered. Continue foot self-inspection daily.",
    attachments: [],
    createdAt: "2024-12-01T09:00:00Z",
  },
  {
    id: "mr004",
    patientId: "p003",
    date: "2024-10-15",
    doctor: "Dr. Emily Carter",
    visitType: "In-person",
    chiefComplaint: "Acute left flank pain, cloudy urine",
    diagnosis: "Suspected Urolithiasis — Left ureter",
    icdCode: "N20.1",
    symptoms: "Acute left flank pain 8/10 onset 6 hours ago, radiating to left lower abdomen and groin. Cloudy urine with burning sensation. No fever. Nausea without vomiting.",
    physicalExam: "CVA tenderness left side +++. Abdomen soft, mildly tender LLQ. No peritoneal signs.",
    vitalSigns: {
      bloodPressure: "138/88",
      heartRate: "96 bpm",
      temperature: "37.0°C",
      oxygenSaturation: "97%",
      weight: "78 kg",
    },
    treatment: "Oral analgesia started. Tamsulosin initiated for medical expulsive therapy. CT urogram ordered to confirm stone size and location. High fluid intake instructed. Urology referral placed given history of recurrent stones.",
    prescribedDrugs: [
      {
        id: "d007",
        name: "Tamsulosin",
        genericName: "Tamsulosin HCl",
        dose: "0.4mg",
        route: "Oral",
        frequency: "Once daily",
        duration: "4 weeks",
        quantity: "28 capsules",
        refills: "No refills",
        instructions: "Take after the same meal each day. May cause orthostatic hypotension.",
        indication: "Medical expulsive therapy",
        startDate: "2024-10-15",
        prescribedBy: "Dr. Emily Carter",
      },
      {
        id: "d008",
        name: "Ibuprofen",
        genericName: "Ibuprofen",
        dose: "400mg",
        route: "Oral",
        frequency: "Three times daily",
        duration: "5 days",
        quantity: "15 tablets",
        refills: "No refills",
        instructions: "Take with food. Avoid if renal function deteriorates. Do not combine with other NSAIDs.",
        indication: "Renal colic pain management",
        startDate: "2024-10-15",
        endDate: "2024-10-20",
        prescribedBy: "Dr. Emily Carter",
      },
    ],
    procedures: "Urinalysis, CT urogram (ordered)",
    urgency: "Semi-urgent",
    followUpIn: "1 week",
    followUpType: "Specialist referral",
    referral: "Urology — Dr. Wallace — for stone management",
    patientEducation: "Strain all urine. Drink 3L water daily. Return immediately if fever > 38.5°C, rigors, or inability to control pain.",
    attachments: [],
    createdAt: "2024-10-15T16:00:00Z",
  },
  {
    id: "mr005",
    patientId: "p006",
    date: "2024-12-10",
    doctor: "Dr. Michael Torres",
    visitType: "Emergency",
    chiefComplaint: "Palpitations, shortness of breath",
    diagnosis: "Atrial Fibrillation with Rapid Ventricular Response",
    icdCode: "I48.91",
    secondaryDiagnoses: "Heart failure with reduced ejection fraction, Anticoagulation therapy",
    symptoms: "Sudden onset palpitations 3 hours ago. Mild dyspnea on minimal exertion. Mild pre-cordial discomfort. No syncope. HR on presentation 128–142 bpm irregular.",
    physicalExam: "Irregularly irregular rhythm. HR 134. Mild bibasal crackles. JVP elevated 5cm. No acute distress.",
    vitalSigns: {
      bloodPressure: "118/74",
      heartRate: "134 bpm",
      temperature: "36.9°C",
      respiratoryRate: "20/min",
      oxygenSaturation: "95%",
      weight: "71 kg",
    },
    treatment: "Rate control achieved with IV Metoprolol boluses. Transitioned to oral rate control. Warfarin anticoagulation continued with INR check. 12-lead ECG performed. Cardiology consultation arranged urgently.",
    prescribedDrugs: [
      {
        id: "d009",
        name: "Metoprolol Tartrate",
        genericName: "Metoprolol Tartrate",
        dose: "5mg",
        route: "IV",
        frequency: "Every 5 minutes",
        duration: "Single dose",
        quantity: "3 vials (max 3 doses)",
        refills: "No refills",
        instructions: "Administer slowly over 1–2 minutes. Monitor HR and BP closely. Hold if HR < 60 or SBP < 90.",
        indication: "Acute rate control — Atrial Fibrillation with RVR",
        startDate: "2024-12-10",
        endDate: "2024-12-10",
        prescribedBy: "Dr. Michael Torres",
      },
      {
        id: "d010",
        name: "Metoprolol Succinate",
        genericName: "Metoprolol Succinate",
        dose: "25mg",
        route: "Oral",
        frequency: "Once daily",
        duration: "Ongoing",
        quantity: "30 tablets",
        refills: "3 refills",
        instructions: "Take with or without food. Do not crush or chew extended-release tablets. Monitor resting HR.",
        indication: "Chronic rate control — Atrial Fibrillation, Heart Failure",
        startDate: "2024-12-10",
        prescribedBy: "Dr. Michael Torres",
      },
      {
        id: "d011",
        name: "Warfarin",
        genericName: "Warfarin Sodium",
        dose: "5mg",
        route: "Oral",
        frequency: "Once daily",
        duration: "Ongoing",
        quantity: "30 tablets",
        refills: "3 refills",
        instructions: "Take at the same time each evening. INR target 2.0–3.0. Avoid vitamin K-rich foods in large quantities. Regular INR monitoring required.",
        indication: "Anticoagulation — Atrial Fibrillation stroke prevention",
        startDate: "2024-12-10",
        prescribedBy: "Dr. Michael Torres",
      },
      {
        id: "d012",
        name: "Furosemide",
        genericName: "Furosemide",
        dose: "40mg",
        route: "Oral",
        frequency: "Once daily",
        duration: "Ongoing",
        quantity: "30 tablets",
        refills: "2 refills",
        instructions: "Take in the morning to avoid nocturia. Monitor potassium levels. Increase if weight gain > 1kg/day.",
        indication: "Volume management — Heart failure with reduced EF",
        startDate: "2024-12-10",
        prescribedBy: "Dr. Michael Torres",
      },
    ],
    procedures: "12-lead ECG, INR check, Chest X-ray, Troponin I x2",
    urgency: "Urgent",
    followUpIn: "48 hours",
    followUpType: "Specialist referral",
    referral: "Cardiology — Dr. Nguyen — urgent inpatient consult",
    patientEducation: "Explained AF and rate control strategy. Emphasised strict Warfarin compliance. Instructed to monitor daily weight and return if dyspnea worsens.",
    attachments: [],
    createdAt: "2024-12-10T08:00:00Z",
  },
];

// Lab results are now file attachments fetched from the API — no mock data needed.
export const MOCK_LAB_RESULTS: LabResult[] = [];

export const MOCK_NOTES: Note[] = [
  {
    id: "n001",
    patientId: "p001",
    authorId: "d001",
    date: "2024-11-20",
    author: "Dr. Emily Carter",
    content: "Patient is highly compliant with medications. Counselled on importance of fluid intake and dietary oxalate restriction. Patient understands need for metabolic stone workup after acute episode resolves.",
  },
  {
    id: "n002",
    patientId: "p001",
    authorId: "d001",
    date: "2024-08-15",
    author: "Dr. Emily Carter",
    content: "Family history of hypertension (father, paternal uncle). Lifestyle modifications discussed including DASH diet, regular exercise. Patient motivated to make dietary changes.",
  },
  {
    id: "n003",
    patientId: "p002",
    authorId: "d002",
    date: "2024-12-01",
    author: "Dr. Michael Torres",
    content: "Patient reports good adherence to Metformin. Mild GI side effects initially but resolved. Referred to dietitian for ongoing support. Weight stable at 72kg.",
  },
];

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: "apt001",
    patientId: "p001",
    patientName: "James Harrison",
    date: "2025-01-15",
    time: "09:00",
    type: "Follow-up - Kidney Stone",
    doctor: "Dr. Emily Carter",
    status: "Scheduled",
  },
  {
    id: "apt002",
    patientId: "p002",
    patientName: "Maria Santos",
    date: "2025-01-18",
    time: "10:30",
    type: "Diabetes Review",
    doctor: "Dr. Michael Torres",
    status: "Scheduled",
  },
  {
    id: "apt003",
    patientId: "p003",
    patientName: "Robert Chen",
    date: "2025-01-12",
    time: "14:00",
    type: "Urology Consult",
    doctor: "Dr. Emily Carter",
    status: "Scheduled",
  },
  {
    id: "apt004",
    patientId: "p004",
    patientName: "Susan Mitchell",
    date: "2025-01-20",
    time: "11:00",
    type: "Thyroid Review",
    doctor: "Dr. Michael Torres",
    status: "Scheduled",
  },
];

export const INITIAL_CHAT_SESSION: ChatSession = {
  id: "session-001",
  messages: [],
  createdAt: new Date().toISOString(),
};

// ─── Patient Portal Mock Data ──────────────────────────────────────────────

export const MOCK_APPOINTMENT_REQUESTS: import("./types").AppointmentRequest[] = [
  {
    id: "ar001",
    patientId: "p001",
    patientName: "James Harrison",
    requestedDate: "2025-02-10",
    requestedTime: "10:00 AM",
    type: "Follow-up",
    reason: "Post-kidney stone follow-up and repeat ultrasound review",
    preferredDoctor: "Dr. Emily Carter",
    status: "Approved",
    createdAt: "2025-01-25T09:00:00Z",
    responseNote: "Confirmed for Feb 10 at 10:00 AM with Dr. Carter.",
  },
  {
    id: "ar002",
    patientId: "p001",
    patientName: "James Harrison",
    requestedDate: "2025-03-05",
    requestedTime: "02:00 PM",
    type: "Lab Review",
    reason: "Review metabolic panel and calcium levels",
    preferredDoctor: "Dr. Emily Carter",
    status: "Pending",
    createdAt: "2025-01-28T11:00:00Z",
  },
  {
    id: "ar003",
    patientId: "p002",
    patientName: "Maria Santos",
    requestedDate: "2025-02-14",
    requestedTime: "09:30 AM",
    type: "General Consultation",
    reason: "Routine diabetes check and HbA1c review",
    preferredDoctor: "Dr. Michael Torres",
    status: "Approved",
    createdAt: "2025-01-20T14:00:00Z",
    responseNote: "Confirmed. Please fast for 8 hours before the appointment.",
  },
];

export const MOCK_LAB_AI_INSIGHTS: import("./types").LabAIInsight[] = [
  {
    id: "ins001",
    labResultId: "lr001",
    patientId: "p001",
    generatedAt: "2024-11-20T15:00:00Z",
    urgency: "Consult Doctor",
    summary:
      "Your urinalysis showed the presence of red blood cells and calcium oxalate crystals, which is consistent with a kidney stone diagnosis. This finding has been reviewed by your doctor.",
    findings: [
      "Red blood cells detected in urine (hematuria)",
      "Calcium oxalate crystals present — most common type of kidney stone",
      "Result is outside the normal range (Abnormal)",
      "Note: Calcium oxalate crystals seen. Consistent with kidney stone.",
    ],
    recommendations: [
      "Increase daily water intake to at least 2.5–3 litres",
      "Reduce foods high in oxalate (spinach, nuts, chocolate)",
      "Follow up with your doctor regarding metabolic stone workup",
      "Strain urine as instructed to capture any passed stone material",
    ],
    disclaimer:
      "This AI-generated insight is for informational purposes only and does not constitute medical advice. Always consult your doctor before making any health decisions.",
  },
  {
    id: "ins002",
    labResultId: "lr002",
    patientId: "p001",
    generatedAt: "2024-11-20T15:05:00Z",
    urgency: "Monitor",
    summary:
      "Your serum creatinine is mildly elevated above the normal range. This may indicate reduced kidney function and should be monitored.",
    findings: [
      "Serum Creatinine: 1.4 mg/dL (reference: 0.7–1.3 mg/dL)",
      "Mildly above the upper limit of normal",
      "May reflect temporary strain on the kidneys from the recent stone episode",
    ],
    recommendations: [
      "Stay well hydrated to support kidney function",
      "Avoid NSAIDs and nephrotoxic medications unless prescribed",
      "Repeat creatinine test at your follow-up appointment",
      "Report any reduced urine output to your doctor",
    ],
    disclaimer:
      "This AI-generated insight is for informational purposes only and does not constitute medical advice. Always consult your doctor before making any health decisions.",
  },
  {
    id: "ins003",
    labResultId: "lr004",
    patientId: "p002",
    generatedAt: "2024-12-01T10:00:00Z",
    urgency: "Monitor",
    summary:
      "Your HbA1c is 7.1%, slightly above the target of <7.0% for people with diabetes. Your doctor has noted this and reinforced dietary guidance.",
    findings: [
      "HbA1c: 7.1% (target: <7.0%)",
      "Reflects average blood glucose over the past 2–3 months",
      "Slightly above the recommended target range",
    ],
    recommendations: [
      "Continue taking Metformin as prescribed",
      "Maintain a low-GI, low-sugar diet",
      "Aim for at least 30 minutes of moderate exercise most days",
      "Monitor blood glucose at home as advised",
      "Attend your next HbA1c check in 3 months",
    ],
    disclaimer:
      "This AI-generated insight is for informational purposes only and does not constitute medical advice. Always consult your doctor before making any health decisions.",
  },
];

export const MOCK_CONSULTATION_REMINDERS: import("./types").ConsultationReminder[] = [
  {
    id: "rem001",
    patientId: "p001",
    type: "follow-up-due",
    title: "Follow-up appointment due",
    message:
      "Your follow-up for the kidney stone episode is due. Dr. Carter recommended a repeat ultrasound and metabolic panel within 4–6 weeks of your emergency visit on Nov 20.",
    dueDate: "2025-01-20",
    priority: "high",
    dismissed: false,
    createdAt: "2025-01-01T08:00:00Z",
  },
  {
    id: "rem002",
    patientId: "p001",
    type: "lab-result-ready",
    title: "New lab results available",
    message:
      "Your recent lab results from Nov 20 are ready to view. Review your urinalysis and serum creatinine results with AI insights in the Lab Results section.",
    dueDate: "2024-11-21",
    priority: "medium",
    dismissed: false,
    createdAt: "2024-11-21T07:00:00Z",
  },
  {
    id: "rem003",
    patientId: "p001",
    type: "medication-refill",
    title: "Tamsulosin refill due",
    message:
      "Your Tamsulosin 0.4mg prescription is due for a refill. You were prescribed 1 refill — contact your pharmacy or request a prescription renewal.",
    dueDate: "2025-01-18",
    priority: "medium",
    dismissed: false,
    createdAt: "2025-01-10T09:00:00Z",
  },
  {
    id: "rem004",
    patientId: "p002",
    type: "lab-result-ready",
    title: "HbA1c results available",
    message:
      "Your HbA1c and fasting glucose results from Dec 1 are now available. Your doctor has reviewed them — check the AI insights for a plain-language summary.",
    dueDate: "2024-12-02",
    priority: "medium",
    dismissed: false,
    createdAt: "2024-12-02T08:00:00Z",
  },
  {
    id: "rem005",
    patientId: "p002",
    type: "annual-checkup",
    title: "Annual eye exam due",
    message:
      "Your annual diabetic eye exam is due. Regular screening is important to detect early signs of diabetic retinopathy. Please book with an ophthalmologist.",
    dueDate: "2025-02-01",
    priority: "medium",
    dismissed: false,
    createdAt: "2025-01-01T08:00:00Z",
  },
  {
    id: "rem006",
    patientId: "p002",
    type: "specialist-referral",
    title: "Urine microalbumin test ordered",
    message:
      "Dr. Torres has ordered a urine microalbumin test to check for early signs of kidney involvement from diabetes. Please visit the lab at your earliest convenience.",
    dueDate: "2025-01-30",
    priority: "low",
    dismissed: false,
    createdAt: "2025-01-05T08:00:00Z",
  },
  {
    id: "rem007",
    patientId: "p003",
    type: "specialist-referral",
    title: "Urology referral pending",
    message:
      "You have been referred to a urologist (Dr. Patterson) for your recurrent kidney stone history. Please contact the urology clinic to schedule your appointment.",
    dueDate: "2025-01-15",
    priority: "high",
    dismissed: false,
    createdAt: "2024-10-16T09:00:00Z",
  },
];
